[package]
name = "memoria"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "memoria-server"
path = "bin/server.rs"

[lib]
name = "memoria"
path = "src/lib.rs"

[dependencies]
ntex = { version = "0.7", features = ["tokio", "rustls"] }
